### ISSUE TITLE
 harbour-qrclip  NOT have a Sailfish icon.

### ISSUE THREAD

**Issue by GNUuser** [monich/harbour-qrclip#8]
Sorry @monich to put to much work to you.  I can not help you  at this  moment on coding, but sure i will in the future making Pull-request instead Open-issues.

**Comment by monich** [comment]
I basically agree, but my graphics design skills suck. I'm open to suggestions :)

**Comment by GNUuser** [comment]
I wil try made a nice icon to  qrclip.

**Comment by monich** [comment]
I must say that I may have quite strong opinion about graphics design elements when I see those and can often even explain what exactly I like or don't like, it's just that I'm having trouble with inventing those myself!

This particular icon I don't really like, but I couldn't come up with anything better than that.

**Comment by JSEHV** [comment]
Maybe this can be closed with pull request #9

**Comment by monich** [comment]
> Maybe this can be closed with pull request #9

Yes, thanks! b11c256 makes it Sailfishy enough, I think:

![harbour-qrclip](https://user-images.githubusercontent.com/5909522/123716393-2485dc80-d883-11eb-94dd-b5a5e6aaaebb.png)

**Comment by monich** [comment]
All right, I'm considering this issue resolved. Version 1.0.9 has the new icon. Closing. Thanks, @JSEHV
